# -*- coding: utf-8 -*-
"""HateSpeechGenerator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOvqyS6-1jytiDerOlUILHGhjILVsNaN
"""

from google.colab import files
uploaded = files.upload()         #downloaded from kaggle

import pandas as pd
import numpy as np
import re
import nltk
import zipfile
import io
import gradio as gr
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


zip_filename = list(uploaded.keys())[0]
zip_content = uploaded[zip_filename]

with zipfile.ZipFile(io.BytesIO(zip_content), 'r') as zf:    #to convert into ZIP
  csv_filename = 'labeled_data.csv'
  with zf.open(csv_filename) as f:
    df = pd.read_csv(f)

df.head()
def clean_text(text):
  text = text.lower()
  text = re.sub(r"http\S+", "", text)
  text = re.sub(r"[^a-zA-Z]", " ", text)
  text = text.strip()
  return text

df["clean_text"] = df["tweet"].apply(clean_text)

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df["clean_text"])
y = df["class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

def predict(text):
  text = clean_text(text)
  vector = vectorizer.transform([text])
  result = model.predict(vector)[0]

  if result == 0:
    return "Hate Speech"
  elif result == 1:
    return "Offensive"
  else:
    return "Neutral"

print(predict("I hate you"))

interface = gr.Interface(
    fn=predict_text,
    inputs="text",
    outputs="text",
    title="Hate Speech Detection System",
    description="Enter text to classify it as: Hate Speech, Offensive Language, or Neutral."
    )

interface.launch(share=True)
